name: CI - Jest Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Mets la version Node.js que tu utilises

      - name: Install dependencies
        run: npm ci

      - name: Vérifier Jest
        run: npx jest --version

      - name: Run tests 
        run: npx jest
	
      - name: Init Git Submodules
        run: git submodule update --init --recursive

